version: '3.1'
services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-server:
    build: statistics
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore_with_me

  ewm-service:
    build: ewm
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore_with_me
      - STATS_SERVER_URL=http://stats-server:9090/hit
